# Generated by Django 4.1.2 on 2023-09-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='status_code',
            field=models.PositiveIntegerField(default=200),
        ),
    ]
